server:
  port: 8762

eureka:
  instance: 
    appname: server-register-center
    #需配置hosts
    hostname: eureka-server-2
  client:
    service-url:
      defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-3:8763/eureka/
      
      