spring:
  application:
    name: service-template
    
eureka:
  client:
    service-url:
       defaultZone: http://eureka-server-1:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

server:
  port: 8773